#!/bin/sh

scp_target="shatow@wraith.shatow.net"
dir="public_html/builds"

if test $# -lt 1; then
 echo "Usage: $0 directory"
 exit 1
fi

#Build hub/leaf
./build -C -n all

#Then package up each cfg
cfgs="`find \"$@\" -name \"*.cfg\" | grep -v \"disabled\"`"
for cfg in $cfgs
do
 if test "`grep 'PACKNAME' $cfg`x" != "x"; then
  #Dont compile, just package up and dont rm old binaries.
  ./build -n -P -q $cfg -s $scp_target:${dir}/ all
 fi
done
chmod 0700 misc/id_dsa
ssh -i misc/id_dsa $scp_target chmod 0644 ${dir}/*.tar.gz
rm *.tar.gz

