#!/bin/sh

if test $# -lt 1; then
 echo "Usage: $0 directory"
 exit 1
fi

#Build hub/leaf
./build -C -n all

#Then package up each cfg
cfgs="`find \"$@\" -name \"*.cfg\"`"
for cfg in $cfgs
do
 if test "`grep 'PACKNAME' $cfg`x" != "x"; then
  #Dont compile, just package up and dont rm old binaries.
  ./build -n -P -p $cfg -s bryan@endurance.quadspeedi.net:public_html/builds/ all
 fi
done
chmod 0700 misc/id_dsa
ssh -i misc/id_dsa bryan@endurance.quadspeedi.net chmod 0644 public_html/builds/*.tar.gz
