#!/bin/sh
if test -z $1
then
  grep -n -R "\"" src/*.c | grep -v "STR(" | grep -v "^src/x" | grep -v "\#include" | grep -v "[\"][^X][\"]" | grep -v "[\"][^X][^X][\"]" | grep -v "\"\"" | grep -v "Context" | grep -v "\#define" | grep -v "stringfix\.c" | grep -v "{\"" | grep -v "BADARGS(" | grep -v "Tcl_" | grep -v "check_tcl_bind(" | grep -v "add_bind_table("
else
  grep -n -R "\"" $1 | grep -v "STR(" | grep -v "^src/x" | grep -v "\#include" | grep -v "[\"][^X][\"]" | grep -v "[\"][^X][^X][\"]" | grep -v "\"\"" | grep -v "Context" | grep -v "\#define" | grep -v "stringfix\.c" | grep -v "^{\"" | grep -v "BADARGS(" | grep -v "Tcl_" | grep -v "check_tcl_bind(" | grep -v "add_bind_table("
fi










