#!/bin/sh
grep=`which grep`
grep "$@" | grep -v "^configure" |grep -v src/bdlib| grep -v "^ChangeLog" | grep -v "^Binary" | grep -v "^src/_" | grep -v "^tmp/" | grep -v "help\..*:" | grep -v "\.svn" | grep -v ".deps.*\.Po" | grep -v "\.c~:" | grep -v "tags:" | grep -v "\.orig:"
