#!/bin/sh
grep=`which grep`
grep "$@" | grep -v "^configure" | grep -v "^ChangeLog" | grep -v "^Binary" | grep -v "^src/_" | grep -v "^tmp/" | grep -v "help\..*:" | grep -v "CVS" | grep -v ".deps.*\.Po" | grep -v "\.c~:"
