#!/bin/sh
make clean
make
echo -n "Partyline pass:	"
read party
echo -n "Admin pass:		"
read admin
echo -n "\"War\" pass:		"
read war
eparty=$(./md5 -s$party)
eadmin=$(./md5 -s$admin)
ewar=$(./md5 -s$war)
echo "set partylinepass \"$eparty\""
echo "set adminpass \"$eadmin\""
echo "set warpass \"$ewar\""
